version: "3.9"

services:
  postgres:
    image: postgres:16 
    container_name: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file: .env
    volumes:
      - ./docker/postgresql/data:/data
    ports:
      - 15432:5432

  pgbouncer:
    image: edoburu/pgbouncer
    container_name: pgbouncer
    env_file: .env
    volumes:
      - ./pgbouncer:/etc/pgbouncer
    ports:
      - "16432:${PGBOUNCER_PORT}"
    depends_on:
      - postgres

  redis:
    image: redis:7
    container_name: redis
    ports:
      - 16379:6379
    volumes:
      - ./docker/redis/data:/data

  backend:
    image: ghcr.io/marcx-ai-monorepo/backend:latest
    restart: always
    env_file: .env
    depends_on:
      - pgbouncer
      - redis

  web:
    image: ghcr.io/marcx-ai-monorepo/web:latest
    restart: always
    env_file: .env

  caddy:
    image: caddy:2
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./caddy/Caddyfile
      - caddy:/data
    depends_on:
      - web
      - backend

