version: "3.9"

services:
  api:
    image: ghcr.io/jasonteh/monorepo-backend:prod
    ports:
      - "4000:4000"
    restart: always

  web:
    image: ghcr.io/jasonteh/monorepo-web:prod
    ports:
      - "3000:3000"
    depends_on:
      - api
    restart: always
