name: Deploy

on:
  push:
    branches:
      - dev
      - staging
      - main

env:
  AWS_REGION: ap-southeast-1
  ECR_REPO_WEB: web
  ECR_REPO_API: backend

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - uses: docker/setup-buildx-action@v3

      - uses: aws-actions/amazon-ecr-login@v2

      - name: Build & Push API
        run: |
          docker build -t $ECR_REPO_API -f .docker/backend/Dockerfile .
          docker tag $ECR_REPO_API:latest ${{ secrets.ECR_API_URI }}:latest
          docker push ${{ secrets.ECR_API_URI }}:latest

      - name: Build & Push Web
        run: |
          docker build -t $ECR_REPO_WEB -f .docker/web/Dockerfile .
          docker tag $ECR_REPO_WEB:latest ${{ secrets.ECR_WEB_URI }}:latest
          docker push ${{ secrets.ECR_WEB_URI }}:latest
